---
title: "HW 03"
author: "Yashi Mi"
format:
  html:
    embed-resources: true
toc: true
---

```{r}
# - loading package manager
if (!require(pacman))
  install.packages(pacman)

# - loading required packages
pacman::p_load(tidyverse,
               here,
               tibble,
               gt,
               reader,
               jpeg,
               grid)
```

## 1 - Du Bois challenge.

```{r}
#| label: label-me-1
income <- read_csv(here("data","income.csv"))
glimpse(income)
```

```{}
```

```{r}
income_long <- income |>
  pivot_longer(cols = c("Rent","Food", "Clothes", "Tax","Other"),
               names_to = "category",
               values_to = "percentage")
glimpse(income)
```

```{r}
img <- readJPEG(here("images","paper-1074131_1280.jpg"))
```

```{r}
income_long$category <- factor(income_long$category, levels =c ("Other", "Tax", "Clothes", "Food", "Rent"))

income_long$Class <- factor(income_long$Class, levels = c("$1000 AND OVER","$750-1000","$500-750","$400-500","$300-400","$200-300","$100-200"))

p<-ggplot(income_long, aes(x=percentage, y=Class,fill=category))+
  
  geom_col(position = "stack")+
  scale_fill_manual(values=c( "Other" = "#F0FFF0",
  "Tax" = "#B0C4DE",
  "Clothes" = "#E8A298",
  "Food" = "#8D6C9F",
  "Rent" = "black"))+
  theme_minimal(base_size = 10)+
  theme (panel.grid.minor = element_blank(),
         panel.grid.major = element_blank(),
         legend.position = "top",
         aspect.ratio = 0.4,
         axis.title.x = element_blank(),
         plot.title = element_text(size = 10))+
geom_text(aes( label = paste0(percentage,"%"),
    color = case_when(
    category == "Rent" ~ "white",
    TRUE ~ "black")),
  position = position_stack(vjust = 0.5),
  size = 2.5,) +
scale_color_identity()+
labs(fill = NULL,
     title = "INCOME AND EXPENDITURE OF 150 NEGRO FAMILIES IN ATLANTA,GA.,U.S.A")
# The following background rendering code was adapted from online sources.
grid::grid.raster(img, width = unit(1, "npc"), height = unit(1, "npc"))
print(p, newpage = FALSE)

```

## 2 - COVID survey - interpret

```{r}
#| label: label-me-2

```

## 3 - COVID survey - reconstruct

## 4 - COVID survey - re-reconstruct

## 5 - COVID survey - another view
